
import { Doctor, Clinic, Medicine } from './types';

export const DISTRICTS = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh', 'Nilphamari'];

export const EMERGENCY_SERVICES = [
  { id: 'e1', name: 'ECG (ইসিজি)', price: 600, icon: '💓', description: 'বাসায় গিয়ে ইসিজি করা হয়' },
  { id: 'e2', name: 'Blood Collection', price: 200, icon: '🩸', description: 'ল্যাব টেস্টের জন্য রক্ত সংগ্রহ' },
  { id: 'e3', name: 'Nurse Care', price: 1500, icon: '👩‍⚕️', description: 'দক্ষ নার্সিং সেবা (১২ ঘণ্টা)' },
  { id: 'e4', name: 'BP Check', price: 100, icon: '🩺', description: 'ব্লাড প্রেসার ও সুগার চেক' },
];

export const LAB_TESTS = [
  { id: 'lt1', name: 'RBS', price: 200 },
  { id: 'lt2', name: 'FBS & 2HRS', price: 400 },
  { id: 'lt3', name: 'S.Creatinine', price: 500 },
  { id: 'lt4', name: 'CBC', price: 600 },
  { id: 'lt5', name: 'SGPT', price: 500 },
  { id: 'lt6', name: 'SGOT', price: 600 },
  { id: 'lt7', name: 'S. Albumin', price: 600 },
  { id: 'lt8', name: 'S. Electrolyte', price: 1200 },
  { id: 'lt9', name: 'HBsAg', price: 400 },
  { id: 'lt10', name: 'HIV', price: 400 },
  { id: 'lt11', name: 'HCV', price: 400 },
  { id: 'lt12', name: 'MP', price: 400 },
  { id: 'lt13', name: 'VDRL', price: 400 },
  { id: 'lt14', name: 'Alkaline Phosphate', price: 500 },
  { id: 'lt15', name: 'Anti HAV-IgM', price: 1200 },
  { id: 'lt16', name: 'Anti HBc- IgM', price: 1500 },
  { id: 'lt17', name: 'Anti HBc-(Total)', price: 1200 },
  { id: 'lt18', name: 'Anti –TPO Ab', price: 1200 },
  { id: 'lt19', name: 'Anti CCP', price: 1800 },
  { id: 'lt20', name: 'Anti -TG Ab', price: 1200 },
  { id: 'lt21', name: 'APTT', price: 800 },
  { id: 'lt22', name: 'ASO Titre', price: 600 },
  { id: 'lt23', name: 'Blood- HCG', price: 1500 },
  { id: 'lt24', name: 'Total + Direct Bilirubin', price: 600 },
  { id: 'lt25', name: 'Total Bilirubin', price: 500 },
  { id: 'lt26', name: 'BT, CT', price: 400 },
  { id: 'lt27', name: 'Blood Grouping & RH Factor', price: 100 },
  { id: 'lt28', name: 'CRP', price: 700 },
  { id: 'lt29', name: 'CA-125', price: 1200 },
  { id: 'lt30', name: 'CA-15-3', price: 1200 },
  { id: 'lt31', name: 'Troponin- I (High Sensitive)', price: 1500 },
  { id: 'lt32', name: 'CBS & ESR', price: 600 },
  { id: 'lt33', name: 'HB %', price: 200 },
  { id: 'lt34', name: 'Cortisol', price: 1200 },
  { id: 'lt35', name: 'D- Dimer', price: 1500 },
  { id: 'lt36', name: 'FNAC', price: 1500 },
  { id: 'lt37', name: 'PSA', price: 1200 },
  { id: 'lt38', name: 'FT3', price: 1200 },
  { id: 'lt39', name: 'FT4', price: 1200 },
  { id: 'lt40', name: 'TSH', price: 1000 },
  { id: 'lt41', name: 'T3', price: 1000 },
  { id: 'lt42', name: 'T4', price: 1000 },
  { id: 'lt43', name: 'PRL', price: 1200 },
  { id: 'lt44', name: 'Testosterone', price: 1200 },
  { id: 'lt45', name: 'Semen Analysis', price: 1000 },
  { id: 'lt46', name: 'Urine R/E', price: 200 },
  { id: 'lt47', name: 'H. Pylori', price: 400 },
  { id: 'lt48', name: 'HBA1C', price: 1200 },
  { id: 'lt49', name: 'Hb-Electroporesis', price: 2000 },
  { id: 'lt50', name: 'S. Calcium', price: 700 },
  { id: 'lt51', name: 'S. Amylase', price: 800 },
  { id: 'lt52', name: 'S. Lipase', price: 800 },
  { id: 'lt53', name: 'Lipid Profile', price: 1200 },
  { id: 'lt54', name: 'Liver Function Test', price: 1200 },
  { id: 'lt55', name: 'Platelet Count', price: 200 },
  { id: 'lt56', name: 'Progesterone', price: 1200 },
  { id: 'lt57', name: 'Prothombin time (INR)', price: 1500 },
  { id: 'lt58', name: 'S. Uric Acid', price: 500 },
  { id: 'lt59', name: 'Skin/Nail Scraping For Fungus', price: 600 },
  { id: 'lt60', name: 'Blood For C/S', price: 1200 },
  { id: 'lt61', name: 'Urine For C/S', price: 800 },
  { id: 'lt62', name: 'Sputum For C/S', price: 1000 },
  { id: 'lt63', name: 'Wound Swab for C/S', price: 800 },
  { id: 'lt64', name: 'Stool R/E', price: 500 },
  { id: 'lt65', name: 'T. HCG', price: 1200 },
  { id: 'lt66', name: 'T. IGE', price: 1200 },
  { id: 'lt67', name: 'Urea', price: 500 },
  { id: 'lt68', name: 'Urine For Albumin', price: 300 },
  { id: 'lt69', name: 'Urine For Pregnancy Test', price: 100 },
  { id: 'lt70', name: 'Vitamin –D', price: 3000 },
  { id: 'lt71', name: 'Widal Test', price: 500 },
  { id: 'lt72', name: 'OGTT', price: 600 },
  { id: 'lt73', name: 'USG of Whole Abdomen', price: 750 },
  { id: 'lt74', name: 'USG of Lower Abdomen', price: 750 },
  { id: 'lt75', name: 'USG of Upper Abdomen', price: 750 },
  { id: 'lt76', name: 'USG of Breast', price: 1800 },
  { id: 'lt77', name: 'USG Of Breast (Single)', price: 1200 },
  { id: 'lt78', name: 'Dengue IgG/IgM Ab', price: 400 },
  { id: 'lt79', name: 'ECG', price: 600 },
  { id: 'lt80', name: 'AMH', price: 1500 },
  { id: 'lt81', name: 'PBF', price: 800 },
  { id: 'lt82', name: 'X-Ray Chest (P/A)', price: 600 },
  { id: 'lt83', name: 'X-Ray Ankle Joint', price: 600 },
  { id: 'lt84', name: 'X-Ray Elbow Joint', price: 600 },
  { id: 'lt85', name: 'X-Ray Knee Joint', price: 600 },
  { id: 'lt86', name: 'KUB', price: 700 },
  { id: 'lt87', name: 'X-Ray L/S', price: 800 },
  { id: 'lt88', name: 'X-Ray Foot', price: 600 },
  { id: 'lt89', name: 'X-Ray Wrist Joint', price: 600 },
  { id: 'lt90', name: 'X-Ray Hand', price: 600 },
  { id: 'lt91', name: 'X-Ray Shoulder Joint', price: 600 },
  { id: 'lt92', name: 'X-Ray Cervical spine', price: 800 },
  { id: 'lt93', name: 'Stool for OBT', price: 1200 },
  { id: 'lt94', name: 'Serum Iron Profile', price: 2000 },
  { id: 'lt95', name: 'Cardiac Profile (Trop-I, CPK, CK-MB)', price: 3500 },
];

export const ABOUT_US_DATA = {
  mission: "আমাদের লক্ষ্য হলো প্রযুক্তির মাধ্যমে স্বাস্থ্যসেবাকে বাংলাদেশের প্রতিটি মানুষের দোরগোড়ায় পৌঁছে দেওয়া।",
  team: [
    { name: "জগদীশ রায়", role: "প্রতিষ্ঠাতা ও সিইও", image: "https://picsum.photos/100/100?u=1" },
    { name: "ডাঃ রফিকুল ইসলাম", role: "প্রধান চিকিৎসা উপদেষ্টা", image: "https://picsum.photos/100/100?u=2" }
  ]
};

export const MEDICINES: Medicine[] = [
  { id: 'm1', name: 'Napa Extend', price: 20, discount: 5, image: 'https://picsum.photos/200/200?med=1', description: 'ব্যথানাশক' },
  { id: 'm2', name: 'Seclo 20', price: 150, discount: 10, image: 'https://picsum.photos/200/200?med=2', description: 'এসিডিটি' },
  { id: 'm3', name: 'Fexo 120', price: 90, discount: 0, image: 'https://picsum.photos/200/200?med=3', description: 'এলার্জি' },
];

export const CLINICS: Clinic[] = [
  { id: 'c-madina', name: 'মদিনা ডায়াগনস্টিক ক্লিনিক এন্ড কনসালটেশন', district: 'Nilphamari', address: 'জেনারেল হাসপাতাল সড়ক ,হাসপাল মোড়, নীলফামারী', doctors: ['md1','md2','md3','md4','md5','md6','md7','md8','md9','md10','md11'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-greensign', name: 'গ্রীন সাইন হাসপাতাল', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['gs1', 'gs2', 'gs3', 'gs4', 'gs5', 'gs6', 'gs7', 'gs8', 'gs9', 'gs10', 'gs11', 'gs12', 'gs13'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ar', name: 'A.R. General Hospital', district: 'Nilphamari', address: 'Sadar Hospital Road, Nilphamari', doctors: ['ar1','ar2','ar3','ar4','ar5','ar6','ar7','ar8','ar9','ar10','ar11'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-mouno', name: 'মৌন জেনারেল হাসপাতাল', district: 'Nilphamari', address: 'নীলফামারী সদর', doctors: ['mou1'], image: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ibadat', name: 'Ibadat Hospital', district: 'Nilphamari', address: 'Old Station Road, Nilphamari', doctors: ['ib1','ib2','ib3','ib4','ib5','ib6','ib7'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
];

export const DOCTORS: Doctor[] = [
  // --- Green Sign Hospital Doctors (Complete 1-13) ---
  { id: 'gs1', name: 'ডাঃ ওবায়দা নাসনীন (মুক্তা)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিজিও (ঢাকা মেডিকেল কলেজ)', specialty: 'স্ত্রী ও প্রসূতি রোগ বিশেষজ্ঞ এবং সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৪টা - রাত ৯টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs1' },
  { id: 'gs2', name: 'ডাঃ শাহ মোঃ মোয়াজ্জেম হোসেন', degree: 'এমবিবিএস (ঢাকা), ডিসিএইচ (শিশু), বিসিএস (স্বাস্থ্য)', specialty: 'নবজাতক ও শিশু রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩টা - রাত ১০টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs2' },
  { id: 'gs3', name: 'ডাঃ আব্দুর রহিম', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডি-অর্থো (বিএসএমএমইউ)', specialty: 'হাড়-জোড়া, বাত ব্যথা ও ট্রমা সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহঃ: বিকাল ৩টা - রাত ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs3' },
  { id: 'gs4', name: 'ডাঃ মোঃ আসাদুজ্জামান (আসাদ)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), এমডি (নিউরোলজি)', specialty: 'নিউরোমেডিসিন এবং মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শুক্রবার: সকাল ১০টা - রাত ৮টা', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs4' },
  { id: 'gs5', name: 'ডাঃ মোঃ আসাদ আলম', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), ডি-কার্ড (বিএসএমএমইউ)', specialty: 'হৃদরোগ, মেডিসিন, উচ্চ রক্তচাপ ও বাতজ্বর বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩টা - রাত ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs5' },
  { id: 'gs6', name: 'ডাঃ মোঃ মেহফুজ আলী', degree: 'এমবিবিএস (র.মে.কু), বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন-এফপি), ডি-কার্ড', specialty: 'মেডিসিন, হৃদরোগ, ডায়াবেটিস, বাত-ব্যথা ও শ্বাসকষ্ট বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহঃ: বিকাল ৩টা - রাত ১০টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs6' },
  { id: 'gs7', name: 'ডাঃ রুমানা আফরোজ', degree: 'এমবিবিএস, পিজিটি, ইওসিটি, ডিএমইউ, সিসিডি, এমপিএইচ', specialty: 'প্রসূতি, বন্ধ্যাত্ব ও স্ত্রী রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহঃ: ৪টা-১০টা; শুক্র: ১০টা-৮টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs7' },
  { id: 'gs8', name: 'ডাঃ মোঃ রাশেদুল ইসলাম (রাশেদ)', degree: 'এমবিবিএস, ডিএলও (বিএসএমএমইউ)', specialty: 'নাক, কান, গলা, হেড নেক সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: সকাল ১০টা - রাত ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs8' },
  { id: 'gs9', name: 'ডাঃ মোঃ সোহরাাব হোসেন', degree: 'এমবিবিএস, এফসিপিএস (সার্জারি)', specialty: 'জেনারেল ও ল্যাপারোস্কপিক সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'শনি-বৃহঃ: বিকাল ৩টা - রাত ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs9' },
  { id: 'gs10', name: 'ডাঃ খন্দকার মোঃ আরিফ হাসনাত', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমডি (অনকোলজি)', specialty: 'ক্যান্সার রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি সোমবার: বিকাল ৩টা - রাত ৯টা', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs10' },
  { id: 'gs11', name: 'ডাঃ ফাহিম কিস্ওয়ার', degree: 'এমবিবিএস, ডিডিভি, সিসিডি, এফএলসিএস, এফসিপিএস', specialty: 'চর্ম, যৌন ও এলার্জি রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শুক্রবার: বিকাল ৩টা - রাত ৯টা', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs11' },
  { id: 'gs12', name: 'ডাঃ মোঃ ইমরান কবীর', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য)', specialty: 'মেডিসিন, ডায়াবেটিস ও মা ও শিশু রোগ চিকিৎসক', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন: বিকাল ৩টা - রাত ৮টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs12' },
  { id: 'gs13', name: 'ডাঃ মোঃ নূরুজ্জামান মিয়া', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (ইউরোলজি)', specialty: 'কিডনি ও ইউরোলজিস্ট সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি মঙ্গলবার: দুপুর ৩টা - রাত ৯টা', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs13' },

  // --- A.R. General Hospital Doctors (Complete 1-11) ---
  { id: 'ar1', name: 'ডাঃ মোঃ মনিরুজ্জামান (মনি)', degree: 'MBBS, BCS, CCD (BIRDEM), MS (Gynae)', specialty: 'প্রসূতি ও স্ত্রীরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: বিকাল ৩টা - রাত ৯টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ar1' },
  { id: 'ar2', name: 'ডাঃ মোঃ শাহ আলম', degree: 'MBBS, BCS, MD (Medicine)', specialty: 'মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহঃ: ৪টা - ৮টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ar2' },
  { id: 'ar3', name: 'ডাঃ মোঃ আশেকুর রহমান', degree: 'MBBS, BCS, FCPS (Med), D-Card, MACP (USA)', specialty: 'মেডিসিন ও হৃদরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শুক্রবার: সকাল ১০টা - রাত ৮টা', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ar3' },
  { id: 'ar4', name: 'ডাঃ মোসাঃ জিন্নাত রেজওয়ানা', degree: 'MBBS, DGO (Gynae)', specialty: 'গাইনী ও প্রসূতি রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: ৪টা - ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar4' },
  { id: 'ar5', name: 'ডাঃ মোঃ মাহবুবুর রহমান', degree: 'MBBS, DCH (Child)', specialty: 'শিশু রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহঃ: ৪টা - ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar5' },
  { id: 'ar6', name: 'ডাঃ মোঃ জাহিদুল ইসলাম', degree: 'MBBS, MS (Surgery)', specialty: 'জেনারেল ও সার্জারি বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: ৫টা - ১০টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ar6' },
  { id: 'ar7', name: 'ডাঃ মোঃ গোলাম সারওয়ার', degree: 'MBBS, D-Ortho', specialty: 'হাড়-জোড়া ও পঙ্গু বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহঃ: ৪টা - ৮টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar7' },
  { id: 'ar8', name: 'ডাঃ মোঃ রেজাউল করিম', degree: 'MBBS, DLO (ENT)', specialty: 'নাক, কান ও গলা বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: ৪টা - ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ar8' },
  { id: 'ar9', name: 'ডাঃ মোঃ নূরুল ইসলাম', degree: 'MBBS, DDV (Skin)', specialty: 'চর্ম ও যৌন রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'শনি-বৃহঃ: ৫টা - ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar9' },
  { id: 'ar10', name: 'ডাঃ মোঃ আবু সাঈদ', degree: 'BDS, PGT (Dental)', specialty: 'দন্ত রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: ৯টা - ৮টা', availableToday: true, rating: 4.6, image: 'https://picsum.photos/200/200?doc=ar10' },
  { id: 'ar11', name: 'ডাঃ মোঃ এনামুল হক', degree: 'MBBS, BCS, MD (Med)', specialty: 'মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'প্রতিদিন: ৪টা - ৮টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar11' },

  // --- Madina Diagnostic Clinic Doctors (Complete 1-11) ---
  { id: 'md1', name: 'ডাঃ মোঃ আব্দুল কাদের জিলানী', degree: 'MBBS, BCS, FCPS (Hematology)', specialty: 'হেমাটোলজি (রক্তরোগ) বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Fri: 9 AM - 3 PM', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=md1' },
  { id: 'md2', name: 'ডাঃ মোঃ কায়কোবাদ হোসেন', degree: 'MBBS, BCS, FCPS, MD (Neurology)', specialty: 'মেডিসিন, নিউরোলজি ও গ্যাস্ট্রোএন্টারোলজি', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Mon-Wed: 3 PM - 8 PM', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=md2' },
  { id: 'md3', name: 'ডাঃ মোস্তাফিজুর রহমান (সাকিব)', degree: 'MBBS, BCS, MD (Nephrology)', specialty: 'কিডনি রোগ ও মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Fri: 4 PM-10 PM, Wed: 9 AM-8 PM', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=md3' },
  { id: 'md4', name: 'ডাঃ আরিফুজ্জামান তুহিন', degree: 'MBBS, BCS, PGT, MD (Cardiology)', specialty: 'হৃদরোগ ও মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Fri: 9 AM - 2 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=md4' },
  { id: 'md5', name: 'ডাঃ মোঃ আব্দুল কুদ্দুস', degree: 'MBBS, BCS, CCD, MCPS (Skin & VD)', specialty: 'চর্ম, যৌন ও এলার্জি রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Sun: 3 PM - 8 PM', availableToday: false, rating: 4.7, image: 'https://picsum.photos/200/200?doc=md5' },
  { id: 'md6', name: 'ডাঃ ধীমান প্রামাণিক', degree: 'MBBS (DMC), BCS, FCPS (ENT)', specialty: 'নাক, কান, গলা রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Tue: 3:30 PM - 8 PM', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=md6' },
  { id: 'md7', name: 'ডাঃ মোঃ মাসুদ পারভেজ', degree: 'MBBS (SSMC), BCS, MD (Medicine)', specialty: 'মেডিসিন, নিউরো-মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Sat-Thu: 4 PM - 8 PM', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=md7' },
  { id: 'md8', name: 'ডাঃ মোঃ আসাদুজ্জামান (সুমন)', degree: 'MBBS, BCS, D-Ortho', specialty: 'হাড়-জোড়া, বাত-ব্যথা ও ট্রমা সার্জন', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Mon: 3 PM - 8 PM', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=md8' },
  { id: 'md9', name: 'ডাঃ মোঃ মনিরুজ্জামান (মনি)', degree: 'MBBS, BCS, CCD, MS (Gynae)', specialty: 'প্রসূতি, বন্ধ্যাত্ব ও স্ত্রীরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Daily', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=md9' },
  { id: 'md10', name: 'ডাঃ ইসরাত আজিজ (সুমি)', degree: 'MBBS, MS (Gynae & Obs)', specialty: 'গাইনী, প্রসূতি ও বন্ধ্যাত্ব বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Fri: 9 AM - 8 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=md10' },
  { id: 'md11', name: 'ডাঃ তাবাসসুম মাহজাবিন', degree: 'MBBS, BCS, FCPS (Pediatrics)', specialty: 'নবজাতক, শিশু ও কিশোর রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-madina'], schedule: 'Daily: 4 PM - 8 PM', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=md11' },

  // --- Mouno General Hospital Doctor ---
  { id: 'mou1', name: 'ডাঃ আব্দুল্লাহ আল মামুন', degree: 'MBBS, MD (Med)', specialty: 'মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-mouno'], schedule: 'শনি-বৃহঃ: ৫টা - ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=mou1' },

  // --- Ibadat Hospital Doctors (Complete 1-7) ---
  { id: 'ib1', name: 'ডাঃ মোঃ মোজাম্মেল হক', degree: 'MBBS, BCS, MD (Med)', specialty: 'মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'প্রতিদিন: ৪টা - ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib1' },
  { id: 'ib2', name: 'ডাঃ মোসাঃ শামীমা আক্তার', degree: 'MBBS, MS (Gynae)', specialty: 'স্ত্রী ও প্রসূতি বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'প্রতিদিন: ৪টা - ১০টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ib2' },
  { id: 'ib3', name: 'ডাঃ মোঃ আতিকুর রহমান', degree: 'MBBS, DCH (Child)', specialty: 'শিশু রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'শনি-বৃহঃ: ৪টা - ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ib3' },
  { id: 'ib4', name: 'ডাঃ মোঃ রবিউল ইসলাম', degree: 'MBBS, D-Ortho', specialty: 'হাড়-জোড়া বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'প্রতিদিন: ৫টা - ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib4' },
  { id: 'ib5', name: 'ডাঃ মোঃ শফিউল আলম', degree: 'MBBS, BCS, FCPS', specialty: 'সার্জারি বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'শনি-বৃহঃ: ৪টা - ৮টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ib5' },
  { id: 'ib6', name: 'ডাঃ মোঃ মাসুদুর রহমান', degree: 'MBBS, DLO', specialty: 'নাক, কান ও গলা বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'প্রতিদিন: ৪টা - ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ib6' },
  { id: 'ib7', name: 'ডাঃ মোঃ আল-আমিন', degree: 'MBBS, BCS, MD (Cardiology)', specialty: 'হৃদরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'শুক্রবার: সকাল ৯টা - বিকাল ৫টা', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib7' },
];
