
import { Doctor, Clinic, Medicine } from './types';

export const DISTRICTS = ['Dhaka', 'Chattogram', 'Sylhet', 'Rajshahi', 'Khulna', 'Barishal', 'Rangpur', 'Mymensingh', 'Nilphamari'];

export const EMERGENCY_SERVICES = [
  { id: 'e1', name: 'ECG (ইসিজি)', price: 800, icon: '💓', description: 'বাসায় গিয়ে ইসিজি করা হয়' },
  { id: 'e2', name: 'Blood Collection', price: 200, icon: '🩸', description: 'ল্যাব টেস্টের জন্য রক্ত সংগ্রহ' },
  { id: 'e3', name: 'Nurse Care', price: 1500, icon: '👩‍⚕️', description: 'দক্ষ নার্সিং সেবা (১২ ঘণ্টা)' },
  { id: 'e4', name: 'BP Check', price: 100, icon: '🩺', description: 'ব্লাড প্রেসার ও সুগার চেক' },
];

export const ABOUT_US_DATA = {
  mission: "আমাদের লক্ষ্য হলো প্রযুক্তির মাধ্যমে স্বাস্থ্যসেবাকে বাংলাদেশের প্রতিটি মানুষের দোরগোড়ায় পৌঁছে দেওয়া।",
  team: [
    { name: "জগদীশ রায়", role: "প্রতিষ্ঠাতা ও সিইও", image: "https://picsum.photos/100/100?u=1" },
    { name: "ডাঃ রফিকুল ইসলাম", role: "প্রধান চিকিৎসা উপদেষ্টা", image: "https://picsum.photos/100/100?u=2" }
  ]
};

export const MEDICINES: Medicine[] = [
  { id: 'm1', name: 'Napa Extend', price: 20, discount: 5, image: 'https://picsum.photos/200/200?med=1', description: 'ব্যথানাশক' },
  { id: 'm2', name: 'Seclo 20', price: 150, discount: 10, image: 'https://picsum.photos/200/200?med=2', description: 'এসিডিটি' },
  { id: 'm3', name: 'Fexo 120', price: 90, discount: 0, image: 'https://picsum.photos/200/200?med=3', description: 'এলার্জি' },
];

export const CLINICS: Clinic[] = [
  { id: 'c-ar', name: 'A.R. General Hospital', district: 'Nilphamari', address: 'Sadar Hospital Road, Nilphamari', doctors: ['ar1','ar2','ar3','ar4','ar5','ar6','ar7','ar8','ar9','ar10','ar11'], image: 'https://images.unsplash.com/photo-1587350859728-117699f8aee1?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-ibadat', name: 'Ibadat Hospital', district: 'Nilphamari', address: 'Old Station Road, Nilphamari', doctors: ['ib1','ib2','ib3','ib4','ib5','ib6','ib7'], image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-mouna', name: 'Mouna General Hospital', district: 'Nilphamari', address: 'Shantinagar, Nilphamari', doctors: ['mo1','mo2'], image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-pacific', name: 'Pacific Lab Zone', district: 'Nilphamari', address: 'Beside Staff Quarter, Nilphamari', doctors: ['pa1','pa2','pa3','pa4','pa5','pa6','pa7'], image: 'https://images.unsplash.com/photo-1512678080530-7760d81faba6?auto=format&fit=crop&q=80&w=800' },
  { id: 'c-greensign', name: 'Green Sign Hospital & Diagnostic', district: 'Nilphamari', address: 'Ukiler Mor, College Road, Nilphamari', doctors: ['gs1','gs2','gs3','gs4','gs5','gs6','gs7','gs8','gs9','gs10','gs11','gs12','gs13'], image: 'https://images.unsplash.com/photo-1538108197003-8ad238b027d4?auto=format&fit=crop&q=80&w=800' },
];

export const DOCTORS: Doctor[] = [
  // A.R. General Hospital Doctors
  { id: 'ar1', name: 'Dr. Md. Moniruzzaman Moni', degree: 'MBBS, BCS, CCD (BIRDEM), MS (Gynae)', specialty: 'প্রসূতি ও স্ত্রীরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Daily: 3 PM - 9 PM', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ar1' },
  { id: 'ar2', name: 'Dr. Md. Moynul Haque Chowdhury', degree: 'MBBS, BCS, FCPS (Urology)', specialty: 'কিডনি ও ইউরোলজি বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Fri: 2 PM - 8 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar2' },
  { id: 'ar3', name: 'Dr. Md. Ashekur Rahman', degree: 'MBBS, BCS, FCPS (Med), D-Card, MACP (USA)', specialty: 'মেডিসিন ও হৃদরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Fri: 10 AM - 8 PM', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ar3' },
  { id: 'ar4', name: 'Dr. Md. Samiur Rahman Shah', degree: 'MBBS, BCS, CCD, MD (Card), FCPS, MACP, MACC', specialty: 'হৃদরোগ ও মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Fri: 10 AM - 8 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar4' },
  { id: 'ar5', name: 'Dr. Rupayan Das', degree: 'MBBS, BCS, D-Ortho (Orthopedics)', specialty: 'হাড়-জোড়া ও বাত-ব্যথা বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Fri: 2 PM - 8 PM', availableToday: false, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ar5' },
  { id: 'ar6', name: 'Dr. Deb Dulal Roy', degree: 'MBBS, BCS, CCD, MD (Psychiatry)', specialty: 'মানসিক রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Thu: 4 PM - 9 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar6' },
  { id: 'ar7', name: 'Dr. Md. Ruhul Amin', degree: 'Associate Professor (Neurology)', specialty: 'নিউরো মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Tue & Fri', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ar7' },
  { id: 'ar8', name: 'Dr. S.M. Towhid Hasan', degree: 'MBBS, BCS, DM, FCPS (Endocrinology)', specialty: 'ডায়াবেটিস ও হরমোন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Fri: 9 AM - 2 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar8' },
  { id: 'ar9', name: 'Dr. Md. Shamsur Rahman', degree: 'Assistant Professor (Medicine)', specialty: 'বাত-ব্যথা ও প্যারালাইসিস বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Sun, Mon, Wed', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ar9' },
  { id: 'ar10', name: 'Dr. Md. Abdul Matin', degree: 'Assistant Professor (Medicine)', specialty: 'মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Sat-Thu: 4 PM - 9 PM', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar10' },
  { id: 'ar11', name: 'Dr. Md. Abdul Awal', degree: 'MBBS, BCS, DCH (Pediatrics)', specialty: 'নবজাতক ও শিশু বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ar'], schedule: 'Daily', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ar11' },

  // Ibadat Hospital Doctors
  { id: 'ib1', name: 'Dr. Kaushik Roy', degree: 'Pediatrics Specialist, Ex-Consultant (Child Dev Center)', specialty: 'নবজাতক, শিশু ও কিশোর রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Sat-Thu: 3 PM - 8 PM', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ib1' },
  { id: 'ib2', name: 'Dr. Sultana Nasery Tuli', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs)', specialty: 'প্রসূতি, স্ত্রীরোগ বিশেষজ্ঞ ও সার্জন', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Sat-Thu: 3:30 PM - 10 PM', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib2' },
  { id: 'ib3', name: 'Dr. Mezbahul Mokarrabeen (Mezba)', degree: 'MBBS, BCS (Health), MS (Urology)', specialty: 'ইউরোলজি বিশেষজ্ঞ ও কিডনি সার্জন', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Fri: 4 PM - 10 PM', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=ib3' },
  { id: 'ib4', name: 'Dr. Munira Ferdous', degree: 'MBBS, DDV, CCD (BIRDEM), DFB', specialty: 'চর্ম ও কসমেটিক সার্জন', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Fri: 10 AM - 4 PM', availableToday: false, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ib4' },
  { id: 'ib5', name: 'Dr. Rezaul Haque', degree: 'MBBS, Advanced Course in Diabetology (USA)', specialty: 'মেডিসিন, ডায়াবেটিস বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Fri: 10 AM - 10 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib5' },
  { id: 'ib6', name: 'Dr. Md. Feroz Hossain', degree: 'MBBS, DLO (BSMMU)', specialty: 'নাক-কান-গলা রোগ বিশেষজ্ঞ সার্জন', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Fri: 10 AM - 5 PM', availableToday: false, rating: 4.7, image: 'https://picsum.photos/200/200?doc=ib6' },
  { id: 'ib7', name: 'Dr. Shakera Akter (Saku)', degree: 'MBBS, BCS (Health), FCPS (Gynae & Obs)', specialty: 'প্রসূতি ও গাইনী বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-ibadat'], schedule: 'Fri: 10 AM - 10 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=ib7' },

  // Mouna General Hospital Doctors
  { id: 'mo1', name: 'Dr. Shankar Kumar Saha', degree: 'MBBS, D-Card (BSMMU), Senior Consultant (Retd.)', specialty: 'হৃদরোগ ও মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-mouna'], schedule: 'Mon: 3 PM - 8 PM, Fri: 11 AM - 5 PM', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=mo1' },
  { id: 'mo2', name: 'Dr. Mahfuza Akter (Lopa)', degree: 'MBBS, BCS (Health), MS (Gynae & Obs)', specialty: 'প্রসূতি ও স্ত্রীরোগ বিশেষজ্ঞ ও সার্জন', districts: ['Nilphamari'], clinics: ['c-mouna'], schedule: 'Fri: 10 AM - 8 PM', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=mo2' },

  // Pacific Lab Zone Doctors
  { id: 'pa1', name: 'Dr. Md. Hafizul Islam', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (গ্যাস্ট্রো), এফসিপিএস (মেডিসিন), সিসিডি (বারডেম)', specialty: 'গ্যাস্ট্রোলিভার, মেডিসিন ও ডায়াবেটিস বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বৃহস্পতিবার (বিকাল ৩টা - রাত ৯টা)', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=pa1' },
  { id: 'pa2', name: 'Dr. Syed Hasan Ali', degree: 'এমবিবিএস, ডি-অর্থো (পঙ্গু হাসপাতাল, ঢাকা)', specialty: 'হাড়-জোড়া, বাত-ব্যথা অর্থোপেডিক বিশেষজ্ঞ ও ট্রমা সার্জন', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শুক্রবার (সকাল ৯টা - রাত ১০টা)', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=pa2' },
  { id: 'pa3', name: 'Dr. Md. Shahjada Mia', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমসিপিএস, এমডি ফেজ-বি (মেডিসিন)', specialty: 'ডায়াবেটিস ও মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শুক্রবার (সকাল ১০ - রাত ৮) ও রবিবার (বিকাল ৫ - রাত ৮)', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=pa3' },
  { id: 'pa4', name: 'Dr. Al-Amin Hossain', degree: 'এমবিবিএস, সিএমইউ (আল্ট্রা), এফসিপিএস (মেডিসিন-শেষ পর্ব), এইচএমও', specialty: 'মেডিসিন, নিউরোমেডিসিন, ডায়াবেটিস, বাত-ব্যথা ও হৃদরোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি সোমবার ও বৃহস্পতিবার (সকাল ১০ - বিকাল ৪)', availableToday: false, rating: 4.7, image: 'https://picsum.photos/200/200?doc=pa4' },
  { id: 'pa5', name: 'Dr. Md. Abu Taher Sabuj', degree: 'এমবিবিএস (ডি.জে.এম.সি)', specialty: 'মেডিসিন, ডায়াবেটিস এন্ড জেনারেল প্রাকটিশনার', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি শনিবার (৯:৩০ - ৫টা) ও মঙ্গলবার (বিকাল ৫ - রাত ৮)', availableToday: false, rating: 4.6, image: 'https://picsum.photos/200/200?doc=pa5' },
  { id: 'pa6', name: 'Dr. Md. Sarowar Hossain', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য)', specialty: 'হাড়-জোড়া, বাত-ব্যথা ও অর্থোপেডিক চিকিৎসক', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতিদিন (দুপুর ২টা - রাত ৯টা)', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=pa6' },
  { id: 'pa7', name: 'Dr. Md. Rabiul Islam', degree: 'এমবিবিএস, এমডি (মেডিসিন)', specialty: 'মেডিসিন, নিউরোমেডিসিন ও বক্ষব্যাধি বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-pacific'], schedule: 'প্রতি বুধবার (দুপুর ২টা - রাত ৮টা)', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=pa7' },

  // Green Sign Hospital Doctors
  { id: 'gs1', name: 'Dr. Obayda Nasnin (Mukta)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিজিও (ডিএমসি)', specialty: 'স্ত্রী ও প্রসূতি রোগ বিশেষজ্ঞ এবং সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন বিকাল ৪টা - রাত ৯টা', availableToday: true, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs1' },
  { id: 'gs2', name: 'Dr. Shah Md. Moazzem Hossain', degree: 'এমবিবিএস (ঢাকা), ডিসিএইচ (শিশু), বিসিএস (স্বাস্থ্য)', specialty: 'নবজাতক ও শিশু রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন বিকাল ৩টা - রাত ১০টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs2' },
  { id: 'gs3', name: 'Dr. Abdur Rahim', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), ডি-অর্থো (বিএসএমএমইউ)', specialty: 'হাড়-জোড়া, বাত ব্যথা, ট্রমা বিশেষজ্ঞ ও সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শনি থেকে বৃহস্পতিবার (বিকাল ৩ - রাত ৯)', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs3' },
  { id: 'gs4', name: 'Dr. Md. Asaduzzaman (Asad)', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), এমডি (নিউরোলজি)', specialty: 'নিউরোমেডিসিন এবং মেডিসিন বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শুক্রবার সকাল ১০টা - রাত ৮টা', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs4' },
  { id: 'gs5', name: 'Dr. Md. Asad Alam', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), সিসিডি (বারডেম), ডি-কার্ড', specialty: 'হৃদরোগ, মেডিসিন, উচ্চ রক্তচাপ ও বাতজ্বর বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন বিকাল ৩টা - রাত ৯টা', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs5' },
  { id: 'gs6', name: 'Dr. Md. Mehfuz Ali', degree: 'এমবিবিএস (র.মে.কু), বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন-এফপি), ডি-কার্ড', specialty: 'মেডিসিন, হৃদরোগ, ডায়াবেটিস, বাত-ব্যথা ও শ্বাসকষ্ট বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শনি থেকে বৃহস্পতিবার (বিকাল ৩ - রাত ১০)', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs6' },
  { id: 'gs7', name: 'Dr. Rumana Afroz', degree: 'MBBS, PGT, EOCT, DMU, CCD, MPH', specialty: 'প্রসূতি, বন্ধ্যাত্ব ও স্ত্রী রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'রবি-সোম (১১-২), শনি-বৃহ (৪-১০), শুক্র (১০-৮)', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs7' },
  { id: 'gs8', name: 'Dr. Md. Rashedul Islam (Rashed)', degree: 'এমবিবিএস, ডিএলও (বিএসএমএমইউ)', specialty: 'নাক, কান, গলা, হেড নেক সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন সকাল ১০টা - রাত ৯টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs8' },
  { id: 'gs9', name: 'Dr. Md. Sohrab Hossain', degree: 'এমবিবিএস, এফসিপিএস (সার্জারি)', specialty: 'জেনারেল ও ল্যাপারোস্কপিক সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শনি থেকে বৃহস্পতিবার (বিকাল ৩ - রাত ৯)', availableToday: true, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs9' },
  { id: 'gs10', name: 'Dr. Khandaker Md. Arif Hasnat', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমডি (অনকোলজি)', specialty: 'ক্যান্সার রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি সোমবার বিকাল ৩টা - রাত ৯টা', availableToday: false, rating: 4.9, image: 'https://picsum.photos/200/200?doc=gs10' },
  { id: 'gs11', name: 'Dr. Fahim Kiswar', degree: 'এমবিবিএস, ডিডিভি, সিসিডি, এফএলসিএস (থাইল্যান্ড)', specialty: 'চর্ম, যৌন ও এলার্জি রোগ বিশেষজ্ঞ', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি শুক্রবার বিকাল ৩টা - রাত ৯টা', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs11' },
  { id: 'gs12', name: 'Dr. Md. Imran Kabir', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য)', specialty: 'মেডিসিন, ডায়াবেটিস ও মা ও শিশু রোগ চিকিৎসক', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতিদিন বিকাল ৩টা - রাত ৮টা', availableToday: true, rating: 4.7, image: 'https://picsum.photos/200/200?doc=gs12' },
  { id: 'gs13', name: 'Dr. Md. Nuruzzaman Mia', degree: 'এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (ইউরোলজি)', specialty: 'কিডনি ও ইউরোলজিস্ট সার্জন', districts: ['Nilphamari'], clinics: ['c-greensign'], schedule: 'প্রতি মঙ্গলবার দুপুর ৩টা - রাত ৯টা', availableToday: false, rating: 4.8, image: 'https://picsum.photos/200/200?doc=gs13' },
];
